gui:
  expandFocusedSidePanel: true
  expandedSidePanelWeight: 4
customCommands:
  - key: "b"
    context: "files"
    command: "mdpreview {{.SelectedFile.Name | quote}}"
    description: "Preview markdown in browser"
    output: terminal
