wtf:
  colors:
    background: "transparent"
    border:
      focusable: "darkslateblue"
      focused: "orange"
      normal: "gray"
  grid:
    columns: [90, 90]
    rows: [24]
  refreshInterval: 5m
  openUrlUtil: "open"
  mods:
    my_prs:
      type: github
      title: "My PRs"
      enabled: true
      position:
        top: 0
        left: 0
        height: 1
        width: 1
      refreshInterval: 5m
      username: "umzo"
      repositories:
        - "asuene/asuene-career"
      showMyPullRequests: true
      showOpenReviewRequests: false
      showStats: false
      enableStatus: false
    review_requests:
      type: cmdrunner
      title: "Review Requests (oldest first)"
      enabled: true
      focusable: false
      position:
        top: 0
        left: 1
        height: 1
        width: 1
      cmd: "gh-review-prs"
      refreshInterval: 5m
